version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pizzadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzadb
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
